INSERT INTO sibe_db.Profesor (DepartamentoId, Nombre, PrimerApellido, SegundoApellido, Email)
VALUES
    (1, 'Andrea', 'Montoya', 'Quesada', 'anmontoya@itcr.ac.cr'),
    (1, 'Aníbal', 'Coto', 'Cortés', 'acotoc@itcr.ac.cr'),
    (1, 'Anibal', 'Ruiz', 'Barquero', 'aniruiz@itcr.ac.cr'),
    (1, 'Carlos Fabián', 'Coto', 'Calvo', 'fcoto@itcr.ac.cr'),
    (1, 'Carlos Mauricio', 'Segura', 'Quiros', 'csegura@itcr.ac.cr'),
    (1, 'Eduardo Interiano', 'Interiano', 'Salguero', 'einteriano@itcr.ac.cr'),
    (1, 'Francisco', 'Navarro', 'Henriquez', 'fnavarro@itcr.ac.cr'),
    (1, 'Hayden Anthony', 'Phillips', 'Brenes', 'hphillips@itcr.ac.cr'),
    (1, 'Hugo', 'Sánchez', 'Ortíz', 'husanchez@itcr.ac.cr'),
    (1, 'Javier', 'Pérez', 'Rodríguez', 'japerez@itcr.ac.cr'),
    (1, 'Johan', 'Carvajal', 'Godínez', 'johcarvajal@itcr.ac.cr'),
    (1, 'Jorge', 'Castro', 'Godinez', 'jocastro@itcr.ac.cr'),
    (1, 'José Alberto', 'Díaz', 'García', 'jdiaz@itcr.ac.cr'),
    (1, 'José Miguel', 'Barboza', 'Retana', 'jmbarboza@itcr.ac.cr'),
    (1, 'Juan Carlos', 'Jiménez', 'Robles', 'juanjimenez@itcr.ac.cr'),
    (1, 'Juan Jose', 'Montero', 'Rodriguez', 'jjmontero@itcr.ac.cr'),
    (1, 'Juan Scott', 'Chaves', 'Noguera', 'jschaves@itcr.ac.cr'),
    (1, 'Laura Cristina', 'Cabrera', 'Quiros', 'lcabrera@itcr.ac.cr'),
    (1, 'Leonardo', 'Sandoval', 'Cascante', 'lesandoval@itcr.ac.cr'),
    (1, 'Marvin', 'Hernández', 'Cisneros', 'marhernandez@itcr.ac.cr'),
    (1, 'Miguel Angel', 'Hernandez', 'Rivera', 'mhernandez@itcr.ac.cr'),
    (1, 'Nestor', 'Hernandez', 'Hostaller', 'nhernandez@itcr.ac.cr'),
    (1, 'Adolfo', 'Chaves', 'Jiménez', 'adchaves@itcr.ac.cr'),
    (1, 'Pablo', 'Alvarado', 'Moya', 'palvarado@itcr.ac.cr'),
    (1, 'Renato', 'Rimolo', 'Donadío', 'rrimolo@itcr.ac.cr'),
    (1, 'Roberto Carlos', 'Molina', 'Robles', 'rmolina@itcr.ac.cr'),
    (1, 'Ronald', 'Soto', 'Fallas', 'rsoto@itcr.ac.cr'),
    (1, 'Ronny', 'Garcia', 'Ramirez', 'rgarcia@itcr.ac.cr'),
    (1, 'Sergio', 'Arriola', 'Valverde', 'sarriola@itcr.ac.cr'),
    (1, 'Sergio Arturo', 'Morales', 'Hernández', 'smorales@itcr.ac.cr'),
    (1, 'William', 'Marín', 'Moreno', 'wmarin@itcr.ac.cr'),
    (1, 'William', 'Quiros', 'Solano', 'wquiros@itcr.ac.cr');
