INSERT INTO sibe_db.Profesor (DepartamentoId, Nombre, PrimerApellido, SegundoApellido, Correo)
VALUES
(1, 'ANDREA', 'MONTOYA', 'QUESADA', 'anmontoya@itcr.ac.cr'),
(1, 'ANIBAL', 'COTO', 'CORTES', 'acotoc@itcr.ac.cr'),
(1, 'ANIBAL', 'RUIZ', 'BARQUERO', 'aniruiz@itcr.ac.cr'),
(1, 'CARLOS FABIAN', 'COTO', 'CALVO', 'fcoto@itcr.ac.cr'),
(1, 'CARLOS MAURICIO', 'SEGURA', 'QUIROS', 'csegura@itcr.ac.cr'),
(1, 'EDUARDO INTERIANO', 'INTERIANO', 'SALGUERO', 'einteriano@itcr.ac.cr'),
(1, 'FRANCISCO', 'NAVARRO', 'HENRIQUEZ', 'fnavarro@itcr.ac.cr'),
(1, 'HAYDEN ANTHONY', 'PHILLIPS', 'BRENES', 'hphillips@itcr.ac.cr'),
(1, 'HUGO', 'SANCHEZ', 'ORTIZ', 'husanchez@itcr.ac.cr'),
(1, 'JAVIER', 'PEREZ', 'RODRIGUEZ', 'japerez@itcr.ac.cr'),
(1, 'JOHAN', 'CARVAJAL', 'GODINEZ', 'johcarvajal@itcr.ac.cr'),
(1, 'JORGE', 'CASTRO', 'GODINEZ', 'jocastro@itcr.ac.cr'),
(1, 'JOSE ALBERTO', 'DIAZ', 'GARCIA', 'jdiaz@itcr.ac.cr'),
(1, 'JOSE MIGUEL', 'BARBOZA', 'RETANA', 'jmbarboza@itcr.ac.cr'),
(1, 'JUAN CARLOS', 'JIMENEZ', 'ROBLES', 'juanjimenez@itcr.ac.cr'),
(1, 'JUAN JOSE', 'MONTERO', 'RODRIGUEZ', 'jjmontero@itcr.ac.cr'),
(1, 'JUAN SCOTT', 'CHAVES', 'NOGUERA', 'jschaves@itcr.ac.cr'),
(1, 'LAURA CRISTINA', 'CABRERA', 'QUIROS', 'lcabrera@itcr.ac.cr'),
(1, 'LEONARDO', 'SANDOVAL', 'CASCANTE', 'lesandoval@itcr.ac.cr'),
(1, 'MARVIN', 'HERNANDEZ', 'CISNEROS', 'marhernandez@itcr.ac.cr'),
(1, 'MIGUEL ANGEL', 'HERNANDEZ', 'RIVERA', 'mhernandez@itcr.ac.cr'),
(1, 'NESTOR', 'HERNANDEZ', 'HOSTALLER', 'nhernandez@itcr.ac.cr'),
(1, 'ADOLFO', 'CHAVES', 'JIMENEZ', 'adchaves@itcr.ac.cr'),
(1, 'PABLO', 'ALVARADO', 'MOYA', 'palvarado@itcr.ac.cr'),
(1, 'RENATO', 'RIMOLO', 'DONADIO', 'rrimolo@itcr.ac.cr'),
(1, 'ROBERTO CARLOS', 'MOLINA', 'ROBLES', 'rmolina@itcr.ac.cr'),
(1, 'RONALD', 'SOTO', 'FALLAS', 'rsoto@itcr.ac.cr'),
(1, 'RONNY', 'GARCIA', 'RAMIREZ', 'rgarcia@itcr.ac.cr'),
(1, 'SERGIO', 'ARRIOLA', 'VALVERDE', 'sarriola@itcr.ac.cr'),
(1, 'SERGIO ARTURO', 'MORALES', 'HERNANDEZ', 'smorales@itcr.ac.cr'),
(1, 'WILLIAM', 'MARIN', 'MORENO', 'wmarin@itcr.ac.cr'),
(1, 'WILLIAM', 'QUIROS', 'SOLANO', 'wquiros@itcr.ac.cr');